1.2 is done
mate-academy/jv-boolean-expression pull request #39
Opened 2019-12-02 11:10 UTC by Dmytro2121

2019-12-02 11:47 UTC, Sofasmile requested changes

2019-12-02 11:47 UTC, Sofasmile commented on src/main/java/core/basesyntax/BooleanExpression.java
> +        if(a)booleanCounter++;
Read task carefully! We should use boolean operators without `if` statement

2019-12-02 13:05 UTC, Sofasmile requested changes

2019-12-02 13:05 UTC, Sofasmile commented on src/main/java/core/basesyntax/BooleanExpression.java
> +                ? true : false;
do we need it `? true : false`?

2019-12-02 13:05 UTC, Sofasmile commented on src/main/java/core/basesyntax/BooleanExpression.java
> +        return ((a && b) && (!c && !d))
good job, but try to simplify

2019-12-02 13:06 UTC, Dmytro2121 commented on src/main/java/core/basesyntax/BooleanExpression.java
> +                ? true : false;
No, actually

2019-12-03 07:37 UTC, Sofasmile approved these changes
God work! But try understanding how it work

2020-03-27 09:51 UTC, closed without merging